#include "gba.h"
#include "logic.h"
#include "graphics.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/sprayer.h"
#include "images/tile.h"
#include "images/welcome.h"
#include "images/gameover.h"
#include "images/tile_welcome.h"

#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    START,
    START_NODRAW,
    APP_INIT,
    APP,
    APP_EXIT,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    // Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while(1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        switch(state) {
        case START:
            // Wait for VBlank
            waitForVBlank();

            drawFullScreenImageDMA(tile_welcome);
            //drawImageDMA(10, 10, 220, 140, welcome);

            state = START_NODRAW;
            break;
        case START_NODRAW:
            // Start the app by switching the state to APP_INIT.
            if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            	state = APP_INIT;
            } else {
            	state = START_NODRAW;
            }

            break;
        case APP_INIT:

        	// Initialize the app. Switch to the APP state.
            initializeAppState(&currentAppState);

            // Draw the initial state of the app
            fullDrawAppState(&currentAppState);

            state = APP;
            break;
        case APP:

            // Process the app for one frame, store the next state
            nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

            // Wait for VBlank before we do any drawing.
            waitForVBlank();

            // Undraw the previous state
            undrawAppState(&currentAppState);

            // // Draw the current state
            drawAppState(&nextAppState);

            //redrawAppState(&currentAppState, &nextAppState);

            // Now set the current state as the next state for the next iter.
            currentAppState = nextAppState;

            if (nextAppState.reset) state = START;

            // Check if the app is exiting. If it is, then go to the exit state.
            if (nextAppState.gameOver) state = APP_EXIT;

            break;
        case APP_EXIT:
            // Wait for VBlank
            waitForVBlank();
            drawFullScreenImageDMA(gameover);
            state = APP_EXIT_NODRAW;
            break;
        case APP_EXIT_NODRAW:
            // Check for a button press here to go back to the start screen
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)
                || KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
                    state = START;
            }
            break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
